version: '3'

services:
  debian-base:
    build:
      context: docker/
      dockerfile: Dockerfile
    image: debian-base:latest

  frontend:
    build:
      context: docker/frontend/
      dockerfile: Dockerfile
    image: frontend:latest
    environment:
      NATS_SERVER_ADDRESS: nats://nats-server:4222
      MAX_REQUESTS_PER_CLIENT: 50
      ADMIN_USERS: alex3galvez@gmail.com joseserranodiaz96@gmail.com victorialservera@gmail.com
    depends_on:
      - debian-base
      - nats-server
      - oauth2-proxy

  debian-worker:
    build:
      context: docker/worker
      dockerfile: Dockerfile
    image: worker:latest
    deploy:
      mode: "replicated"
      replicas: 3
    environment:
      NATS_SERVER_ADDRESS: nats://nats-server:4222
      MAX_SECONDS_EXECUTION_PER_REQUEST: 20
    depends_on:
      - debian-base
      - nats-server

  debian-observer:
    build:
      context: docker/observer
      dockerfile: Dockerfile
    image: observer:latest
    environment:
      NATS_SERVER_ADDRESS: nats://nats-server:4222
    depends_on:
      - debian-base
      - nats-server

  debian-injector:
    build:
      context: docker/injector
      dockerfile: Dockerfile
    image: injector:latest
    environment:
      NATS_SERVER_ADDRESS: nats://nats-server:4222
    depends_on:
      - debian-base
      - nats-server

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream -m 8222"

  oauth2-proxy:
    ports:
      - "4180:4180"
    image: bitnami/oauth2-proxy:latest
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_UPSTREAMS: "http://frontend:8080"
      OAUTH2_PROXY_CLIENT_ID: 936638621086-ukfhb28p7pkbjup42pgvjq4br9ce0h86.apps.googleusercontent.com
      OAUTH2_PROXY_CLIENT_SECRET: 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
      OAUTH2_PROXY_COOKIE_SECRET: _-vsNPgMZKXBRGWutZsIgeyB9Dzx-4aRNQwfX-zuDyo=
      OAUTH2_PROXY_HTTPS_REDIRECT: "false"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
    restart: always